### ISSUE TITLE
Spring boot: JSP not found (404)-Springboot

### ISSUE THREAD

**Issue by KhoeLe** [jaygajera17/E-commerce-project-springBoot#22]
When I have a cloned project and am having trouble loading the web with 404 status error

**Comment by KhoeLe** [comment]
Yes I try, but not working with expect .

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jaygajera17** [comment]
i havn't ios . but default land page is login page that must be showing .

**Comment by KhoeLe** [comment]
This has been resolved when I start intellij IEDEA  and also if I chose vscode still had error.

**Comment by Bervvv** [comment]
I use intellij IEDEA and has the same issue.

`Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Jul 21 01:30:16 PDT 2023
There was an unexpected error (type=Not Found, status=404).
JSP file [/views/userLogin.jsp] not found`

**Comment by Bervvv** [comment]
Solved jsp file not found issue:

main-directory           <---- Content from original repo (not a java project)
--java-project-directory <----- JAVA project created here
----src
------main
--------webapp
----------WEB-INF
------------view
--------------index.jsp

Open the file from java-project-directory rather than main-directory. So for this project, use the IDE to open `JtProject` rather than `E-commerce-project-springBoot`. 

Reference: https://stackoverflow.com/a/66246935

**Comment by nsrg5601** [comment]
sir we are unable to add the data to table
we are getting the login age after that its showing invalid user name nad password for which you have given
